### ISSUE TITLE
Return response body of non-200 requests

### ISSUE THREAD

**Issue by vilterp** [lukewestby/elm-http-extra#1]
Use case: I'm building a test harness in Elm for an API that returns 400 Bad Requests a lot with a helpful error message as the body and need to display that error message in the UI.

Not sure exactly what the API should look like — maybe allow providing a decoder for errors as well, or just make an `Error` type in which the `BadResponse` constructor contains a `Body`?

**Comment by etaque** [comment]
I had to write my own `handleResponse` for that, also see https://github.com/evancz/elm-http/pull/12

Maybe add a `withJsonBody` that sets a customised `handleResponse`?

**Comment by lukewestby** [comment]
We definitely should not continue to use `Http.Error` for this reason, but I'd like for us to decide: should this package be responsible for the response at all? On the one hand, we could just hand off the `Task RawError Response` for the user to work with on their own. If we decide that we'd like to help the user deal with responses, though, I think we should be thorough and design a system that provides the same ease of use for handling responses and errors as we currently provide for constructing requests.

**Comment by lukewestby** [comment]
Personally I'd prefer to design some APIs around responses and errors because I think it would be fun 😄 but we should make the right choice for the users

**Comment by lukewestby** [comment]
Personally I'd prefer to design some APIs around responses and errors because I think it would be fun 😄 but we should make the right choice for the users

**Comment by lukewestby** [comment]
@vilterp @etaque what do you think about this? https://github.com/lukewestby/elm-http-extra/pull/6

**Comment by vilterp** [comment]
Looks good to me!

**Comment by etaque** [comment]
yes :+1:

**Comment by lukewestby** [comment]
published 3.0.1! thanks folks :smile:
