### ISSUE TITLE
Who's using this?

### ISSUE THREAD

**Issue by lukewestby** [lukewestby/elm-http-extra#10]
@splodingsocks let me know that Kuali is and now I'm curious!

**Comment by ghost** [comment]
just started using it today

**Comment by alex-kovshovik** [comment]
I'm using it in https://github.com/aspushkinus/hobo-elm and I'm working on a PR to upgrade this package for Elm 0.17. Problem is tests are not even upgraded for Elm 0.16 and I need a small test app to test my changes.
