### ISSUE TITLE
Needs tests

### ISSUE THREAD

**Issue by ghost** [lukewestby/elm-http-extra#11]
It'd be good if there were tests so that I could verify everything is working.

**Comment by lukewestby** [comment]
Agreed! I'm planning to add tests and examples and maybe a longer tutorial this week.

**Comment by Istar-Eldritch** [comment]
I might get into the tests today if @lukewestby has not started yet.

**Comment by ghost** [comment]
:beers:

**Comment by lukewestby** [comment]
@Istar-Eldritch feel free!

**Comment by lukewestby** [comment]
@cjhowe @Istar-Eldritch i've added some unit tests (still waiting on a PR to node-elm-test before i can get good coverage on some of the Body stuff), we'll still need integration tests to verify that things work correctly end-to-end and function as working examples for folks. Gonna leave this issue open until those are complete.

**Comment by lukewestby** [comment]
I also want to add tests to some of the internal task translation stuff, but we'll wait on that until I can do some restructuring after this is re-released as elm-http-builder for 0.17
