### ISSUE TITLE
Query string builder

### ISSUE THREAD

**Issue by etaque** [lukewestby/elm-http-extra#3]
I'm wondering if it's a good idea to add some helpers for query string building, could be useful but naming strategies depends on the backend implementation (lists, nested fields).

Thoughts?

**Comment by lukewestby** [comment]
I think this is a good idea. I left it out at first because `Http` exposes `url`, but in reference to #2 as well, I'd love if installing this package didn't require the installation of `Http` at all.

**Comment by lukewestby** [comment]
For now I'm going to export `Http.url` directly so folks won't need to import `Http` in order to construct urls with query strings using key-value pairs. I'll publish a new release with that after the rename tomorrow

**Comment by lukewestby** [comment]
Do you think exporting `Http.url` covers this need for now? It's in v2.0.0

**Comment by etaque** [comment]
yes, that's perfect!
