### ISSUE TITLE
Rename to elm-http-flow

### ISSUE THREAD

**Issue by lukewestby** [lukewestby/elm-http-extra#4]
cc @etaque

What do you think is the safest way to go about renaming a package without breaking too many people's setups? Luckily this is only a week old now and shouldn't be too impactful 😄

**Comment by etaque** [comment]
The repo rename should be transparent as it's redirected, and for package the current one will stay as elm-http-extra so it shouldn't break anything?

Another name could be elm-http-builder: not fancy but more descriptive :)

**Comment by lukewestby** [comment]
If this repo is renamed from elm-http-extra to elm-http-[new name] and elm-package goes to look up lukewestby/elm-http-extra@1.2.2, will github know to redirect the request?

**Comment by etaque** [comment]
Yes, it should. But if we want to be sure, that can be tested with a toy repo.

**Comment by lukewestby** [comment]
The people have spoken https://twitter.com/luke_dot_js/status/692711770595680256

elm-http-builder it is. i'll do the rename tomorrow

**Comment by lukewestby** [comment]
Wait! `HttpBuilder` or `Http.Builder`?

**Comment by etaque** [comment]
My personal preference goes to HttpBuilder, dots in module names feels weird to me so I usually rename them in my imports :)

**Comment by lukewestby** [comment]
Let's do this after 0.17 comes out, I think it'll ease the transition since folks won't be able to use the old versions with 0.17.

**Comment by lukewestby** [comment]
I'm gonna close until then
