### ISSUE TITLE
Can't handle error bodies that aren't JSON

### ISSUE THREAD

**Issue by lukewestby** [lukewestby/elm-http-extra#7]
Thanks for @fredcy for catching this!

If your server returns a body on a 404 error for example that looks like `"Not found."` the error will always be a JSON decoding failure because `"Not found."` isn't valid JSON. It would need to be `"\"Not found.\""` to be decoded as a `String`. We need some way to let the error body be grabbed as a string without decoding.

**Comment by fredcy** [comment]
(Sorry, I should have opened this issue myself.)

The HTML response body in the case that gave me trouble was exactly this:

```
404 page not found
```

As you say, that's not valid JSON as there are no surrounding quotes. The error return that I get from the `Http.Extra.send` task is `UnexpectedPayload ("Unexpected token p")` which might mean that the Json parser read "404" as valid Json but could not accept anything more.

**Comment by lukewestby** [comment]
Solved (hopefully) in 5.0.0! I'm gonna close this and if it ends up being buggy still we'll reopen.

**Comment by fredcy** [comment]
Works great. Thanks. I now get a `BadResponse` value for the case of an Http 404 and the `data` element of that has the (non-JSON) text of the response body.
